### ISSUE TITLE
By default, set response to output JSON

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/xtrest#11]
Now you have to do it for every method

```
	response.contentType = ContentType.APPLICATION_JSON
```

it would be nice if this could be default behavior.
It works if you have a client application, but if you are running in a client like Advanced REST client, you see only "Raw output"

![image](https://user-images.githubusercontent.com/4549002/29069201-40e9da6c-7c10-11e7-8d71-b42b5cf7c3b4.png)

Otherwise, you see also JSON output:

![image](https://user-images.githubusercontent.com/4549002/29069229-62d634ea-7c10-11e7-8c59-4e88adb3430b.png)

**Comment by tinchodias** [comment]
+1

**Comment by tinchodias** [comment]
In fact, I'm still confused with the origin of the variable "response", so it'd good to do not have to use it :) 

Eclipse shows me it's a kind of hidden method parameter, so I guess it's something of the magic of Xtend that I still don't know.

**Comment by tinchodias** [comment]
I explored and implemented a fix for this issue in commit b95aa9e36ecafb4c5b8d26827943452aeed1a828

I only tested it manually in a local project. Also tested to override the content type to plain text and works. 

What is missing is to release a new version if you agree.

**Comment by fdodino** [comment]
Nice! Go ahead!

**Comment by tinchodias** [comment]
Buh... release to maven central didn't work. However, new versions were created in repo. I followed the guide to deploy at uqbar, so not sure what's wrong. Maybe some change I made months ago at .travis.yml. Now I need to sleep.
