### ISSUE TITLE
Generate parent project for xtrest project

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/xtrest#17]
Just to add 1.1.3 xtrest dependency and also a build configuration like this

```xml
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>fully.qualified.MainClass</mainClass>
						</manifest>
					</archive>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

So we can avoid manual configuration for students.
It's a nice to have feature.

**Comment by fdodino** [comment]
fully.qualified.MainClass, hahaha, didn't realize about that.
Cancelling issue.

**Comment by tinchodias** [comment]
I added this mvn command-line support for the particular case of libros example here: 

https://github.com/uqbar-project/eg-libros-angularJS-ES6-xtrest/blob/master/pom.xml

but could be great for the general case.
