### ISSUE TITLE
Update Usage in readme

### ISSUE THREAD

**Issue by tinchodias** [uqbar-project/xtrest#4]
I had errors in the derived file with this kind of actions:
@Get('/libros/:id')

until I discovered there is a 0.1.4 version that works, versus the version in the readme:

```
 <dependency>
    <groupId>org.uqbar</groupId>
    <artifactId>xtrest</artifactId>
    <version>0.1.3</version>
 </dependency>
```

should I create a PR?

**Comment by fdodino** [comment]
Already fixed by  you, @tinchodias  :smile:
Closing it
